version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: narralog-db
    environment:
      POSTGRES_DB: narralog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"